=== 359539857/tandong/liantong/AdminCenter/src/main/resources/ActionFramewrok.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3school.com.cn" xmlns:tns="http://www.w3school.com.cn"
	elementFormDefault="qualified">

	<element name="ActionBusConfig" type="tns:ActionBusConfigType"></element>
	<element name="Parameter" type="tns:ParameterType"></element>
	<element name="ActionPluginConfig" type="tns:ActionPluginConfigType"></element>
	<element name="ImportResource" type="tns:ImportResourceType"></element>

	<element name="HadoopServerGroup" type="tns:HadoopGroupType"></element>
	<element name="HadoopServer" type="tns:HadoopServerType"></element>

	<element name="ResultPath" type="tns:ResultPathType"></element>

	<complexType name="ActionBusConfigType">
		<sequence>
			<element ref="tns:ImportResource" maxOccurs="unbounded" minOccurs="0"></element>
			<element ref="tns:Parameter" maxOccurs="unbounded" minOccurs="0"></element>
			<element ref="tns:HadoopServerGroup" maxOccurs="unbounded" minOccurs="0" />
			<element ref="tns:ActionPluginConfig" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:ResultPath" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="DefaultUseCacheGroup" type="string"></attribute>
		<attribute name="DefaultUseHadoopGroup" type="string"></attribute>
	</complexType>

	<complexType name="ParameterType">
		<attribute name="Name" type="string" use="required"></attribute>
		<attribute name="Value" type="string" use="required"></attribute>
		<attribute name="Description" type="string"></attribute>
	</complexType>

	<complexType name="ActionPluginConfigType">
		<sequence>
			<element name="PluginXMLResource" maxOccurs="unbounded" minOccurs="0">
				<complexType>
					<attribute name="Path" type="string"></attribute>
				</complexType>
			</element>
		</sequence>
		<attribute name="AutoScanPath" type="string"></attribute>
	</complexType>

	<complexType name="ImportResourceType">
		<attribute name="Path" type="string"></attribute>
		<attribute name="Description" type="string"></attribute>
	</complexType>

	<complexType name="HadoopServerType">
		<attribute name="Name" type="string"></attribute>
		<attribute name="IP" type="string"></attribute>
		<attribute name="Prot" type="string"></attribute>
	</complexType>

	<complexType name="HadoopGroupType">
		<sequence>
			<element ref="tns:HadoopServer" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="Id" type="string"></attribute>
	</complexType>

	<complexType name="ResultPathType">
		<attribute name="Path" type="string"></attribute>
	</complexType>
</schema>

=== 359539857/tandong/liantong/AdminCenter/target/classes/ActionFramewrok.xml
<?xml version="1.0" encoding="UTF-8"?>
<ActionBusConfig xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3school.com.cn ActionFramewrok.xsd">

	<ImportResource Path="local.properties" Description="导入本地资源文件 " />
	<Parameter Name="load" Value="1" Description="定义全局参数" />
	<Parameter Name="guid" Value="dfds.fdf" Description="定义全局参数" />

	<HadoopServerGroup Id="hodoop0">
		<HadoopServer Name="Slave" IP="127.0.0.1" Prot="53200" />
	</HadoopServerGroup>

	<ActionPluginConfig AutoScanPath="com.liantong.web.action" />

	<ResultPath Path="/WEB-INF/pages" />
</ActionBusConfig>
