=== 359539857/tandong/ctoframework/cto-service/src/main/resources/ServiceFramework.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3school.com.cn" xmlns:tns="http://www.w3school.com.cn"
	elementFormDefault="qualified">

	<element name="ServiceBusConfig" type="tns:ServiceBusConfigType"></element>
	<element name="Parameter" type="tns:ParameterType"></element>
	<element name="DataSourceGroup" type="tns:DataSourceGroupType"></element>
	<element name="Property" type="tns:PropertyType"></element>
	<element name="DataSource" type="tns:DataSourceType"></element>
	<element name="ServicePluginConfig" type="tns:ServicePluginConfigType"></element>
	<element name="ImportResource" type="tns:ImportResourceType"></element>
	<element name="SingleDataSource" type="tns:DataSourceType"></element>
	<element name="ReadWriteDataSource" type="tns:ReadWriteDataSourceType"></element>

	<element name="MemCacheServerGroup" type="tns:MemCacheServerGroupType"></element>
	<element name="CacheServer" type="tns:CacheServerType"></element>
	<element name="Server" type="tns:ServerType"></element>

	<element name="HadoopServerGroup" type="tns:HadoopGroupType"></element>
	<element name="HadoopServer" type="tns:HadoopServerType"></element>

	<group name="SystemDataSourceGroup">
		<choice>
			<element ref="tns:DataSourceGroup" maxOccurs="unbounded" minOccurs="0"></element>
			<element ref="tns:SingleDataSource" maxOccurs="1" minOccurs="0"></element>
			<element ref="tns:ReadWriteDataSource" maxOccurs="1" minOccurs="0"></element>
		</choice>
	</group>

	<complexType name="ServiceBusConfigType">
		<sequence>
			<element ref="tns:ImportResource" maxOccurs="unbounded" minOccurs="0"></element>
			<element ref="tns:Parameter" maxOccurs="unbounded" minOccurs="0"></element>
			<group ref="tns:SystemDataSourceGroup"></group>
			<element ref="tns:MemCacheServerGroup" maxOccurs="unbounded" minOccurs="0"></element>
			<element ref="tns:HadoopServerGroup" maxOccurs="unbounded" minOccurs="0" />
			<element ref="tns:ServicePluginConfig" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="DefaultUseCacheGroup" type="string"></attribute>
		<attribute name="DefaultUseHadoopGroup" type="string"></attribute>
		<attribute name="ServiceListenerIntervalTime" type="long"></attribute>
	</complexType>

	<complexType name="ParameterType">
		<attribute name="Name" type="string" use="required"></attribute>
		<attribute name="Value" type="string" use="required"></attribute>
		<attribute name="Description" type="string"></attribute>
	</complexType>

	<complexType name="DataSourceGroupType">
		<sequence>
			<element ref="tns:DataSource" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
		<attribute name="Id" type="string" use="required"></attribute>
		<attribute name="Description" type="string"></attribute>

	</complexType>

	<complexType name="DataSourceType">
		<sequence>
			<element name="Property" type="tns:PropertyType" maxOccurs="unbounded" minOccurs="1" />
		</sequence>
		<attribute name="PoolClass" type="tns:PoolClassType" use="required"></attribute>
		<attribute name="Id" type="string" use="required"></attribute>
		<attribute name="Description" type="string"></attribute>
	</complexType>

	<complexType name="PropertyType">
		<attribute name="Name" type="string" use="required"></attribute>
		<attribute name="Value" type="string" use="required"></attribute>
		<attribute name="Description" type="string"></attribute>
	</complexType>

	<simpleType name="PoolClassType">
		<restriction base="string">
			<enumeration value="com.mchange.v2.c3p0.ComboPooledDataSource"></enumeration>
			<enumeration value="org.apache.commons.dbcp.BasicDataSource"></enumeration>
			<enumeration value="org.logicalcobwebs.proxool.ProxoolDataSource"></enumeration>
			<enumeration value="com.jolbox.bonecp.BoneCPDataSource"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="ServicePluginConfigType">
		<sequence>
			<element name="PluginXMLResource" type="tns:PluginXMLResourceType" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
		<attribute name="AutoScanPath" type="string"></attribute>
	</complexType>

	<complexType name="ImportResourceType">
		<attribute name="Path" type="string"></attribute>
		<attribute name="Description" type="string"></attribute>
	</complexType>

	<complexType name="PluginXMLResourceType">
		<attribute name="Path" type="string"></attribute>
	</complexType>

	<complexType name="ReadWriteDataSourceType">
		<sequence>
			<element ref="tns:DataSource" maxOccurs="2" minOccurs="2"></element>
		</sequence>
	</complexType>

	<complexType name="MemCacheServerGroupType">
		<sequence>
			<element ref="tns:CacheServer" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="Id" type="string"></attribute>
	</complexType>

	<complexType name="CacheServerType">
		<sequence>
			<element ref="tns:Server" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="Id" type="string"></attribute>
		<attribute name="MaxIdleTime" type="int"></attribute>
		<attribute name="MinConnCount" type="int"></attribute>
		<attribute name="MaxConnCount" type="int"></attribute>
		<attribute name="InitConnCount" type="int"></attribute>
	</complexType>

	<complexType name="ServerType">
		<attribute name="Port" type="int"></attribute>
		<attribute name="IP" type="string"></attribute>
	</complexType>

	<complexType name="HadoopServerType">
		<attribute name="Name" type="string"></attribute>
		<attribute name="IP" type="string"></attribute>
		<attribute name="Prot" type="string"></attribute>
	</complexType>

	<complexType name="HadoopGroupType">
		<sequence>
			<element ref="tns:HadoopServer" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="Id" type="string"></attribute>
	</complexType>
</schema>

=== 359539857/tandong/liantong/COSBusinessCenter/target/classes/ServiceFramework.xml
<?xml version="1.0" encoding="UTF-8"?>
<ServiceBusConfig xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3school.com.cn ServiceFramework.xsd" DefaultUseCacheGroup="cache0"
	DefaultUseHadoopGroup="hadoop0">


	<ImportResource Path="local.properties" Description="导入本地资源文件 " />
	<Parameter Name="load" Value="1" Description="定义全局参数" />
	<Parameter Name="guid" Value="dfds.fdf" Description="定义全局参数" />

	<DataSourceGroup Id="localDataGroup">
		<DataSource PoolClass="com.mchange.v2.c3p0.ComboPooledDataSource" Id="read">
			<Property Name="driverClass" Value="${import.jdbc.driverClass}"></Property>
			<Property Name="jdbcUrl" Value="${import.jdbc.url}"></Property>
			<Property Name="user" Value="${import.jdbc.userName}"></Property>
			<Property Name="password" Value="${import.jdbc.password}"></Property>
			<!-- 指定连接池中保留的最大连接数. Default:15 -->
			<Property Name="maxPoolSize" Value="${c3p0.maxPoolSize}" />
			<!-- 指定连接池中保留的最小连接数 -->
			<Property Name="minPoolSize" Value="${c3p0.minPoolSize}" />
			<!-- 指定连接池的初始化连接数 取值应在minPoolSize 与 maxPoolSize 之间.Default:3 -->
			<Property Name="initialPoolSize" Value="${c3p0.initialPoolSize}" />
			<!-- 最大空闲时间,60秒内未使用则连接被丢弃。若为0则永不丢弃。 Default:0 -->
			<Property Name="maxIdleTime" Value="${c3p0.maxIdleTime}" />
			<!-- 当连接池中的连接耗尽的时候c3p0一次同时获取的连接数. Default:3 -->
			<Property Name="acquireIncrement" Value="${c3p0.acquireIncrement}" />
			<!-- JDBC的标准,用以控制数据源内加载的PreparedStatements数量。但由于预缓存的statements属于单个connection而不是整个连接池所以设置这个参数需要考虑到多方面的因数.如果maxStatements与maxStatementsPerConnection均为0,则缓存被关闭。Default:0 -->
			<Property Name="maxStatements" Value="${c3p0.maxStatements}" />
			<!-- 每60秒检查所有连接池中的空闲连接.Default:0 -->
			<Property Name="idleConnectionTestPeriod" Value="${c3p0.idleConnectionTestPeriod}" />
			<!-- 定义在从数据库获取新连接失败后重复尝试的次数。 Default:30 -->
			<Property Name="acquireRetryAttempts" Value="${c3p0.acquireRetryAttempts}" />
			<!-- 获取连接失败将会引起所有等待连接池来获取连接的线程抛出异常。但是数据源仍有效保留,并在下次调用getConnection()的时候继续尝试获取连接。如果设为true,那么在尝试获取连接失败后该数据源将申明已断开并永久关闭。Default:false -->
			<Property Name="breakAfterAcquireFailure" Value="${c3p0.breakAfterAcquireFailure}" />
			<!-- 银性能消耗大请只在需要的时候是哟个它。如果设为true,那么在每个connection提交的时候都将校验其有效性。建议使用idleConnectionTestPeriod或automaticTestTable等提升连接测试的性能。 
				Default:false -->
			<Property Name="testConnectionOnCheckout" Value="${c3p0.testConnectionOnCheckout}" />
		</DataSource>
		<DataSource PoolClass="com.mchange.v2.c3p0.ComboPooledDataSource" Id="write">
			<Property Name="driverClass" Value="${import.jdbc.driverClass}"></Property>
			<Property Name="jdbcUrl" Value="${import.jdbc.url}"></Property>
			<Property Name="user" Value="${import.jdbc.userName}"></Property>
			<Property Name="password" Value="${import.jdbc.password}"></Property>
			<!-- 指定连接池中保留的最大连接数. Default:15 -->
			<Property Name="maxPoolSize" Value="${c3p0.maxPoolSize}" />
			<!-- 指定连接池中保留的最小连接数 -->
			<Property Name="minPoolSize" Value="${c3p0.minPoolSize}" />
			<!-- 指定连接池的初始化连接数 取值应在minPoolSize 与 maxPoolSize 之间.Default:3 -->
			<Property Name="initialPoolSize" Value="${c3p0.initialPoolSize}" />
			<!-- 最大空闲时间,60秒内未使用则连接被丢弃。若为0则永不丢弃。 Default:0 -->
			<Property Name="maxIdleTime" Value="${c3p0.maxIdleTime}" />
			<!-- 当连接池中的连接耗尽的时候c3p0一次同时获取的连接数. Default:3 -->
			<Property Name="acquireIncrement" Value="${c3p0.acquireIncrement}" />
			<!-- JDBC的标准,用以控制数据源内加载的PreparedStatements数量。但由于预缓存的statements属于单个connection而不是整个连接池所以设置这个参数需要考虑到多方面的因数.如果maxStatements与maxStatementsPerConnection均为0,则缓存被关闭。Default:0 -->
			<Property Name="maxStatements" Value="${c3p0.maxStatements}" />
			<!-- 每60秒检查所有连接池中的空闲连接.Default:0 -->
			<Property Name="idleConnectionTestPeriod" Value="${c3p0.idleConnectionTestPeriod}" />
			<!-- 定义在从数据库获取新连接失败后重复尝试的次数。 Default:30 -->
			<Property Name="acquireRetryAttempts" Value="${c3p0.acquireRetryAttempts}" />
			<!-- 获取连接失败将会引起所有等待连接池来获取连接的线程抛出异常。但是数据源仍有效保留,并在下次调用getConnection()的时候继续尝试获取连接。如果设为true,那么在尝试获取连接失败后该数据源将申明已断开并永久关闭。Default:false -->
			<Property Name="breakAfterAcquireFailure" Value="${c3p0.breakAfterAcquireFailure}" />
			<!-- 银性能消耗大请只在需要的时候是哟个它。如果设为true,那么在每个connection提交的时候都将校验其有效性。建议使用idleConnectionTestPeriod或automaticTestTable等提升连接测试的性能。 
				Default:false -->
			<Property Name="testConnectionOnCheckout" Value="${c3p0.testConnectionOnCheckout}" />
		</DataSource>
	</DataSourceGroup>

	<MemCacheServerGroup Id="cache0">
		<CacheServer Id="mainId0" MaxIdleTime="5" MinConnCount="2" MaxConnCount="30" InitConnCount="2">
			<Server Port="11211" IP="127.0.0.1" />
		</CacheServer>
	</MemCacheServerGroup>

	<HadoopServerGroup Id="hodoop0">
		<HadoopServer Name="Slave" IP="127.0.0.1" Prot="53200" />
	</HadoopServerGroup>

	<ServicePluginConfig AutoScanPath="com.liantong.service">
	</ServicePluginConfig>
</ServiceBusConfig>
